---
title: "Sankey Charts"
author: "Patrick Freeman"
output: html_document
  
---


```{r setup, include=FALSE}
## Global options
#knitr::opts_chunk$set(cache = TRUE)



library(highcharter)
library(openxlsx)
library(tidyverse)
library(readr)
library(here)
library(glue)
library(skimr)
library(labelled)
library(haven)



dsn <- "example_2022-01-05_SPSS_Allrespondents (n=1110).sav"


dat_raw <- read_sav(here("data", dsn))



dat <- dat_raw %>% 
  filter(status == "complete" | status == "Complete") %>% 
  dplyr::select(respid, status, dcountry, dmonth, dspeciality, matches("b16[bcde]"), matches("^dqd23[abcde]"), matches("^qd23")) %>% 
  filter(dmonth %in% c(4,5,6)) %>% 
  mutate(dmonth = "Month-1",
         dcountry = glue::glue("Market {dcountry}"))

ref_products <- openxlsx::read.xlsx(here("docs", "product_sankey.xlsx"))


# current share

vars_keep <- c("respid", "dcountry", "dmonth", "dspeciality")

dat_line <- dat %>% 
  dplyr::select(all_of(vars_keep), matches("b16b")) %>% 
  mutate_if(haven::is.labelled, as.numeric) %>% 
  pivot_longer(
    -c(all_of(vars_keep)),
    names_to = c("qid", "patient_record"),
    names_sep = "_",
    values_to = "qb16b" # represents current line
  ) %>% 
  dplyr::select(-qid) %>% 
  mutate_at(vars(patient_record), as.numeric)


dat_records <- dat %>% 
  dplyr::select(respid, dcountry, dmonth, matches("b16[cde]")) %>% 
  mutate_at(vars(matches("b16")), as.numeric) %>% 
  pivot_longer(
    -c(respid, dcountry, dmonth), 
    names_to = c("qid", "patient_record"),
    names_sep = "_",
    values_to = "tx_code"
  ) %>% 
  mutate(
    patient_record = as.numeric(patient_record),
  ) %>% 
  pivot_wider(
    names_from = "qid",
    values_from = "tx_code"
  ) 

dat_current <- dat %>% 
  labelled::remove_labels() %>% 
  dplyr::select(respid, dcountry, matches("^dqd23[abcde]")) %>% 
  pivot_longer(
    cols = matches("^dqd23[abcde]"),
    names_to = c("qid"),
    values_to = "product_code",
    names_transform = list(product_code = as.integer)) %>% 
  dplyr::mutate(patient_record = str_sub(qid, start = -1, end = -1)) %>% 
  mutate(patient_record = case_when(patient_record == "a" ~ 1,
                                    patient_record == "b" ~ 2,
                                    patient_record == "c" ~ 3,
                                    patient_record == "d" ~ 4,
                                    patient_record == "e" ~ 5),
         patient_record = as.numeric(patient_record),
  ) %>% 
  select(-qid) %>%
  drop_na(product_code) %>% 
  left_join(ref_products, by = "product_code") %>% 
  rename(current = product_code, current_product = product)

# intended share

dat_intended <- dat %>% 
  dplyr::select(respid, dcountry, dmonth, matches("^qd23")) %>% 
  mutate_at(vars(matches("qd23")), as.numeric) %>% 
  pivot_longer(
    -c(respid, dcountry, dmonth), 
    names_to = c("qid", "patient_record"),
    names_sep = "_",
    values_to = "qd23a"
  ) %>% 
  mutate(
    patient_record = as.numeric(patient_record),
  ) %>% 
  left_join(dat_line, by = c("respid", "patient_record", "dcountry", "dmonth")) %>% 
  left_join(dat_records, by = c("respid", "patient_record", "dcountry", "dmonth")) %>% 
  mutate(
    hr_type_intended = case_when(
      # 1st LoT & 2nd gen ARI in 1st trt
      qb16b == 1 & qd23a %in% c(3, 6, 20) ~ 1,
      # 2nd LoT & 1st trt not 2nd gen ARI, 2nd trt 2nd gen ARI
      qb16b == 2 & !(qb16c %in% c(3, 6, 20)) & (qd23a %in% c(3, 6, 20)) ~ 1,
      # 3rd LoT & 1st trt not 2nd gen ARI, 3rd trt 2nd gen ARI
      qb16b == 3 & !(qb16c %in% c(3, 6, 20)) & !(qb16d %in% c(3, 6, 20)) & (qd23a %in% c(3, 6, 20)) ~ 1,
      TRUE ~ 0
    ),
    hr_type_intended_product = case_when(hr_type_intended == 1 ~ qd23a)) %>% 
  drop_na(qb16b) %>%
  filter(hr_type_intended == 1) %>% 
  dplyr::select(respid, dcountry, patient_record, product_code = hr_type_intended_product) %>% 
  left_join(ref_products, by = "product_code") %>% 
  rename(intended_type = product_code, intended_product = product)


# Joined current and intended


dat_sankey <- dat_current %>% 
  left_join(dat_intended, by = c("respid", "dcountry", "patient_record")) %>%
  drop_na(intended_product) %>% 
  mutate(label = "Intended ",
         intended_product = glue::glue("{label}{intended_product}")) %>% 
  select(dcountry, current_product, intended_product) %>% 
  arrange(current_product, intended_product)



node_color_list <- list(list(id = 'Product 3', color="#D7E4BD"),
                        list(id = 'Product 2', color="#A2A6FC"),
                        list(id = 'Product 4', color="#F8C0AA"),
                        list(id = 'Product 1', color="#A4C579"),
                        list(id = 'Product 5', color="#A6A6A6"),
                        list(id = 'Intended Product 3', color="#8AAC46"),
                        list(id = 'Intended Product 2', color="#5058FA"),
                        list(id = 'Intended Product 4', color="#F39069"))



plot_sankey <- function(market){
  sank_dat <- dat_sankey %>% 
    filter(dcountry == market) %>%
    select(current_product, intended_product)
    
    
    
  plot <- hchart(data_to_sankey(sank_dat), "sankey", name = glue::glue("{market}"), nodes = node_color_list) %>%
          hc_plotOptions(series = list(dataLabels = list(style = list(fontSize = "9.5px", color = "#000000")))) %>% 
          hc_title(text= glue::glue("{market} Current Products to Intended Products"))
          
    
    return(plot)
}

```

# {.tabset}

## Market 1

```{r, echo=FALSE, fig.width=9.5, fig.height=6}
plot_sankey(market = "Market 1")
```


## Market 2

```{r, echo=FALSE, fig.width=9.5, fig.height=6}
plot_sankey(market = "Market 2")
```

## Market 3

```{r, echo=FALSE, fig.width=9.5, fig.height=6}
plot_sankey(market = "Market 3")
```

## Market 4

```{r, echo=FALSE, fig.width=9.5, fig.height=6}
plot_sankey(market = "Market 4")
```


## Market 5

```{r, echo=FALSE, fig.width=9.5, fig.height=6}
plot_sankey(market = "Market 5")
```


